### ISSUE TITLE
The module removes "default_config_hash" when updating

### ISSUE THREAD

**Issue by msnassar** [openeuropa/oe_corporate_blocks#106]
The module removes "default_config_hash" when updating (drush updb). 
This is because (_oe_corporate_blocks_import_corporate_links) is overriding all existing (exported) configs with the one defined in config/post_update (e,g, [config/post_update/40002_update_footer_data/oe_corporate_blocks.ec_data.footer.yml](https://github.com/openeuropa/oe_corporate_blocks/pull/98/files#diff-163e6bf39e8925535ab6ce5eb97f3e6a0d95e259c6370c26445e4c620ee5f43d))

https://github.com/openeuropa/oe_corporate_blocks/pull/98/files#diff-02346775307e755b6765448e54eec646057bb22b836797cce4d59b1d6643e846R197

**Comment by 22Alexandra** [comment]
@msnassar could you please check again on 4.x dev branch and update the status of the current issue?

**Comment by AaronGilMartinez** [comment]
Closing, old issue with PR to solve it and no response, thanks
