### ISSUE TITLE
How to properly connect and set up Apache Jena Fuseki

### ISSUE THREAD

**Issue by Okenite1** [openeuropa/oe_corporate_blocks#133]
Hi, 
I would like to know how to properly set up and configure Apache Jena Fuseki instead of Virtuoso to properly use it with Drupal 9 and then install the footer.

And, if it is possible, to know how to automatically import rdf into it

**Comment by brummbar** [comment]
Hello,
we don't use Jena Fuseki so we don't have first-hand experience. I suggest to take a look at the Easyrdf library, which is used to make the sparql connection. They have a dockerfile with Fuseki https://github.com/easyrdf/easyrdf/tree/main/docker .
