### ISSUE TITLE
Some URLs in EU footer are using http protocol instead of https

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_corporate_blocks#136]
In the EU footer config there are 7 URLs that are using `http` although the sites are all using `https`:

https://github.com/openeuropa/oe_corporate_blocks/blob/4.14.0/config/install/oe_corporate_blocks.eu_data.footer.yml#L25
https://github.com/openeuropa/oe_corporate_blocks/blob/4.14.0/config/install/oe_corporate_blocks.eu_data.footer.yml#L28
https://github.com/openeuropa/oe_corporate_blocks/blob/4.14.0/config/install/oe_corporate_blocks.eu_data.footer.yml#L31
https://github.com/openeuropa/oe_corporate_blocks/blob/4.14.0/config/install/oe_corporate_blocks.eu_data.footer.yml#L37
https://github.com/openeuropa/oe_corporate_blocks/blob/4.14.0/config/install/oe_corporate_blocks.eu_data.footer.yml#L43
https://github.com/openeuropa/oe_corporate_blocks/blob/4.14.0/config/install/oe_corporate_blocks.eu_data.footer.yml#L49
https://github.com/openeuropa/oe_corporate_blocks/blob/4.14.0/config/install/oe_corporate_blocks.eu_data.footer.yml#L52

Version: 4.14.0

**Comment by AaronGilMartinez** [comment]
Hello, @kp77 Footer URLs were updated in 4.19.0 (#152) thanks, closing
