### ISSUE TITLE
Access denied to /admin/config/corporate-blocks for admin user (uid 1)

### ISSUE THREAD

**Issue by giucas-falchetto** [openeuropa/oe_corporate_blocks#141]
I can't access corporate-blocks admin page.  Even using admin user I get a 403 error.
Drupal logs report this message:
`Path: /admin/config/corporate-blocks. Drupal\Core\Http\Exception\CacheableAccessDeniedHttpException: in Drupal\Core\Routing\AccessAwareRouter->checkAccess() (line 115 of [...]/web/core/lib/Drupal/Core/Routing/AccessAwareRouter.php).`

any help will be appreciated

**Comment by nagyad** [comment]
We will have a look at the issue, in the meantime you can access the related configurations under `admin/config/footer_link_general` path.

**Comment by monfranco** [comment]
as discussed during the Ask OEL Team meeting 14/06/2024. the reporter will provide the contribution

**Comment by brummbar** [comment]
Will be fixed in #163 .

**Comment by brummbar** [comment]
#163 merged, the route was not used and it has been removed.
