### ISSUE TITLE
Call to a member function isSource() on null

### ISSUE THREAD

**Issue by Aporie** [openeuropa/oe_corporate_blocks#158]
In oe_corporate_blocks_post_update_40010 some string translations are deleted.

If the website deleted the block after installation of the module, these strings are not existing and result in the following error:

```
[notice] Update started: oe_corporate_blocks_post_update_40010
Error: Call to a member function isSource() on null in /home/ec2-user/environment/eurofound-d8-dev/web/core/modules/locale/src/StringDatabaseStorage.php on line 293 #0 /home/ec2-user/environment/eurofound-d8-dev/web/core/modules/locale/src/StringDatabaseStorage.php(189): Drupal\locale\StringDatabaseStorage->dbStringKeys()
```

Patch attached.
[oe_corporate_blocks_delete_string_optional.txt](https://github.com/user-attachments/files/15888969/oe_corporate_blocks_delete_string_optional.txt)

**Comment by brummbar** [comment]
Hello @Aporie , we fixed this in #159 and tagged a 4.19.2 release. Thanks for reporting the issue.
