### ISSUE TITLE
Post update hook fails when Interface translation is not enabled.

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_corporate_blocks#48]
In our project we still use the 1.x branch and had an error because of a [post update hook](https://github.com/openeuropa/oe_corporate_blocks/blob/1.x/oe_corporate_blocks.post_update.php#L27), that uses the locale.storage service.

After discussing with the team, we found that this could also be an issue [on branch 2.x](https://github.com/openeuropa/oe_corporate_blocks/blob/2.x/oe_corporate_blocks.post_update.php#L30).

The error message we recieved:

>  [notice] Update started: oe_corporate_blocks_post_update_10001
>  [error]  You have requested a non-existent service "locale.storage". 
>  [error]  Update failed: oe_corporate_blocks_post_update_10001 
>  [error]  Update aborted by: oe_corporate_blocks_post_update_10001

**Comment by brummbar** [comment]
Hi @kp77 , we added a ticket on our board and fix it as soon as possible.

**Comment by nagyad** [comment]
Closing the issue, it is resolved by the PRs above.
