### ISSUE TITLE
New footer guidelines

### ISSUE THREAD

**Issue by mirba** [openeuropa/oe_corporate_blocks#60]
Hello, I would like to know if there is an estimate of when the new footer look will be implemented?
Thank you,
Miriam

This is the old footer that is being installed with the oe_corporate_blocks
![image](https://user-images.githubusercontent.com/3542228/96000546-50694b00-0e37-11eb-85df-7a6857660626.png)

This is the footer look that is required according to the new guidelines
![image](https://user-images.githubusercontent.com/3542228/96000604-5c550d00-0e37-11eb-810e-962648c5a87e.png)

**Comment by kimlop** [comment]
@mirba to date it is already implemented, you could close the issue

**Comment by AaronGilMartinez** [comment]
Closing, old issue, already implemented
